[package]
name = "valence_command"
version.workspace = true
edition.workspace = true

[dependencies]
bevy_ecs.workspace = true
valence_core.workspace = true
anyhow.workspace = true
glam.workspace = true
serde_json.workspace = true
valence_block.workspace = true
valence_nbt.workspace = true
valence_entity.workspace = true
valence_instance.workspace = true